spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


