spring:
  mongodb:
    uri: mongodb://localhost:27017/faculty_db
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  rabbitmq:
    password: ${RABBIT_PASSWORD}
    username: ${RABBIT_USERNAME}
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
file:
  upload: ${FILE_DIRECTORY}