spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mongodb:
    uri: mongodb://localhost:27017/fileRecords
  rabbitmq:
    password: ${RABBIT_PASSWORD}
    username: ${RABBIT_USERNAME}
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
server:
  port:
    8084
storage:
  url: ${ENDPOINT}
  accessKey: ${USERNAME}
  secretKey: ${PASSWORD}