spring:
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  mongodb:
    uri: mongodb://localhost:27017/vic_application
  rabbitmq:
    password: ${RABBIT_PASSWORD}
    username: ${RABBIT_USERNAME}
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
server:
  port: 8000
storage:
  minio:
    bucket-objects: buket-object
    bucket-layout: buket-layout
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password123