package com.final_project.notification_service.model;
public enum NotificationType {
    // Account lifecycle
    USER_REGISTERED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    EMAIL_VERIFIED,
    ACCOUNT_LOCKED,

    // Invitations
    SYSTEM_INVITATION,
    REPOSITORY_INVITATION,

    // Blog interactions
    BLOG_NEW_COMMENT,        // COMMENT_CREATED
    BLOG_COMMENT_REPLY,      // COMMENT_REPLIED
    BLOG_POST_LIKED,         // ARTICLE_LIKED
    BLOG_POST_SHARED,        // ARTICLE_SHARED
    BLOG_POST_PUBLISHED,     // ARTICLE_PUBLISHED


    REPOSITORY_PUSH,
    REPOSITORY_INVITATION_SENT,
    REPOSITORY_INVITATION_ACCEPTED,
    REPOSITORY_INVITATION_DECLINED,
    REPOSITORY_BRANCH_CREATED,
    REPOSITORY_BRANCH_MERGED,
    REPOSITORY_PULL_REQUEST_OPENED,
    REPOSITORY_PULL_REQUEST_MERGED,
    REPOSITORY_TASK_ASSIGNED,
    REPOSITORY_TASK_SUBMITTED,
    REPOSITORY_TASK_COMPLETED,
    REPOSITORY_TASK_DEADLINE_REMINDER,
    // Generic
    CUSTOM
}
