spring:
  application:
    name: blog-service
  config:
    import:
      - optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog_db
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USERNAME:guest}
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:8444/realms/final-project
          jwk-set-uri: http://localhost:8444/realms/final-project/protocol/openid-connect/certs
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
server:
  port: 8087
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: false
    include-binding-errors: always

logging:
  level:
    root: info
    com:
      final_project:
        blog_service:
          model:
            Article: DEBUG
#    org:
#      springframework:
#        web: INFO
#        data:
#          mongodb: DEBUG
#        security: TRACE



app:
  file-upload:
    max-image-size: 10485760
    max-video-size: 536870912
  service:
    auth-url: http://auth-service
    file-url: http://file-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
