spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOriginPatterns:
#              - "http://localhost:5173"
#              - "http://localhost:*"
#              - "http://127.0.0.1:*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - PATCH
#              - OPTIONS
#            allowedHeaders:
#              - "*"
#            allowCredentials: true
#            maxAge: 3600

server:
  port: 8080
  shutdown: graceful
  address: 0.0.0.0