package com.final_project.versioncontrolservice.model;


public enum RepositoryEventType {
    REPOSITORY_PUSHED,
    REPOSITORY_PULLED,
    REPOSITORY_FETCHED,
    REPOSITORY_CLONED,

    REPOSITORY_INVITATION_SENT,
    REPOSITORY_INVITATION_ACCEPTED,
    REPOSITORY_INVITATION_DECLINED,

    REPOSITORY_CREATED,
    REPOSITORY_DELETED,
    REPOSITORY_RENAMED,
    REPOSITORY_VISIBILITY_CHANGED,

    BRANCH_CREATED,
    BRANCH_DELETED,
    BRANCH_MERGED,

    COMMIT_CREATED,
    PULL_REQUEST_OPENED,
    PULL_REQUEST_MERGED,
    PULL_REQUEST_CLOSED,

    MILESTONE_CREATED,
    TASK_ASSIGNED,
    TASK_SUBMITTED,
    TASK_COMPLETED,
    TASK_DEADLINE_REMINDER,

}
